"""empty message

Revision ID: 91ecbc51db2a
Revises: 6b33dbdd560b
Create Date: 2024-06-06 00:55:37.074670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ecbc51db2a'
down_revision = '6b33dbdd560b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_planet', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'planet', ['current_planet'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_planet')

    op.drop_table('planet')
    # ### end Alembic commands ###
